
vertex_shader: 'shaders/def.vs.glsl'
fragment_shader: 'shaders/def.fs.glsl'

show_colliders: false

font: 'data/font/0.png'
font_config: 'data/font/font.yaml'

button_textures:
  normal: 'data/button_normal.png'
  hover: 'data/button_hover.png'
  active: 'data/button_active.png'

sprites:
  bird: 'data/bird.png'
  back: 'data/back.png'
  tube: 'data/tube.png'
